### ISSUE TITLE
ONT

### ISSUE THREAD

**Issue by shimbalama** [jingmeng-bioinformatics/Deepssv#1]
Hi, do you expect this approach to work with ONT data? If so do you have a pre trained model?

Liam

**Comment by jingmeng-bioinformatics** [comment]
What do you mean by ONT?

**Comment by shimbalama** [comment]
Oxford Nanopore

**Comment by jingmeng-bioinformatics** [comment]
Yes, it can work with ONT data. And you can find the pre-trained model in the folder named model
