### ISSUE TITLE
Pre-trained DeepSSV models?

### ISSUE THREAD

**Issue by kiranchari** [jingmeng-bioinformatics/Deepssv#3]
Are there pre-trained DeepSSV models? I am not able to find any pre-trained checkpoints that I can use to run on a new sample.

Also, how can I reproduce the results of DeepSSV on the benchmark samples (MB, CLL etc.)?

**Comment by jingmeng-bioinformatics** [comment]
Thanks for your interest. Please find the pre-trained model in the folder named model.

**Comment by jingmeng-bioinformatics** [comment]
You can use the pre-trained model on the benchmark samples. However, the original FASTQ files of MB and CLL are of diverse sequencing libraries as well. Library L.A gives relatively high evenness of coverage genome-wide, so we chose to use its sequencing files. Sequencing depths for tumor and normal samples are 40× and 30×, respectively. The BAM files provided in the original publication were not used directly. Instead, we first used BWA to map the reads in the downloaded FASTQ files to the human reference genome hg38/GRCh8 with default settings, then marked PCR and optical duplicates with Picard and finally realigned the raw gapped alignment and adjusted base quality scores with GATK.
